version: '3'
services:
    server: 
        build:
            context: .
            dockerfile: Dockerfile.server
        ports: 
            - 4000:4000
    app: 
        build: .
        environment: 
            - "VUE_APP_API_URL=http://localhost:4000"
        ports: 
            - 5000:5000    
        